### ISSUE TITLE
node-rdkafka version

### ISSUE THREAD

**Issue by denneulin** [waldophotos/kafka-avro#16]
Hi,

I see you use the version 0.7.0-ALPHA.3 of node-rdkafka whereas the actual one is 2.0.0.

Do you plan to update your kafka-avro to deal with this new version of node-rdkafka or at least with the v1 ?

**Comment by thanpolas** [comment]
Hey @denneulin, I'm on a break right now, if this is important to you feel free to submit a PR and I will accept it.

I didn't even look but I'd assume there are breaking changes from 0.7 to 2.0?
