### ISSUE TITLE
Please beta test 0.8.0

### ISSUE THREAD

**Issue by thanpolas** [waldophotos/kafka-avro#19]
Need beta testers for the new `0.8.0-beta.1` version which has been published on npm with the tag `beta`.

### Changelog

- **v0.8.0-beta.1**, *09 Nov 2017*
    - Provides option to fetch all past versions of a topic (thank you [CMTegner](https://github.com/CMTegner).
    - Provides option to select which topics should be fetched.

### New features

New options when instantiating kafka-avro:

* `topics` **Array of Strings** You may optionally define specific topics to be fetched by kafka-avro vs fetching schemas for all the topics which is the default behavior.
* `fetchAllVersions` **Boolean** Set to true to fetch all versions for each topic, use it when updating of schemas is often in your environment.

### Test Cases

1. Run kafka-avro as you normally would, the default behavior is to fetch the latest schema for all topics.
1. Enable the `fetchAllVersions` option and produce on an older version from an external producer, see if the message gets properly parsed.
1. Define specific topics to be fetched using the `topics` option, check that only specific topics are fetched.
1. Use `fetchAllVersions` in combination with `topics` and check expected results (legacy producer + limited topics).

I am sorry I cannot run those tests, as mentioned on #3 testing is dodgy with the current tooling and I have been long gone from the company that required this library so my local setup isn't up to speed.

Once this version checks out I will proceed with publishing proper.

The `0.8.0-beta.1` version is on the `schema-fetch-updates` branch.

ping @giannisp @codeburke @cmtegner

**Comment by CMTegner** [comment]
This is great!

I found a bug when using `fetchAllVersions: true`, fixed in #20.

I'm unable to use `topics` because it expects there to be a pair of (`-key`, `-value`) subjects per topic. We only use key-serialisers for a few topics, and for the rest we use strings (which don't require a schema). This results in 404 errors for the topics that have no `-key` subject. Perhaps we can fail gracefully on 404 when trying to expand subjects from `selectedTopics`? Alternatively we can force the user to provide the subjects instead of the topics.

**Comment by thanpolas** [comment]
Nice! I've merged your PR and softened the errors when fetching versions so it won't break the operation via #21 

I have released 0.8.0-beta.2 on the beta channel, let me know how this fares @CMTegner

**Comment by CMTegner** [comment]
Found a few more issues: #22. With these fixes it seems to work well for us.

I've begun work on upgrading node-rdkafka, and it looks like there won't be many changes. The main difference is that the `Topic` constructor is no longer public (i.e. you just pass in strings), and the streaming-API is standalone (like the producer and consumer constructors). I'll hopefully have something ready later this week/early next week.

**Comment by thanpolas** [comment]
Nice technique with the `.filter(Boolean)` wasn't aware of that, merged and published `0.8.0-beta.3` @CMTegner

**Comment by CMTegner** [comment]
Beta 3 works great for us!

**Comment by thanpolas** [comment]
cool, let's wait one more week @CMTegner and then I'll release proper.

**Comment by thanpolas** [comment]
@CMTegner @giannisp 0.8.0 has been released on npm
