### ISSUE TITLE
avsc and the readiness of kafka-avro

### ISSUE THREAD

**Issue by tannad** [waldophotos/kafka-avro#26]
Hi,

I am using the node-rdkafka with avsc for avro but that doesn't seem to work, I was curious to know the status and readiness of kafka-avro, can you kindly let me know. 

Many thanks,
D Tanna

**Comment by thanpolas** [comment]
Have you followed the instructions at [Initialize kafka-avro](https://github.com/waldophotos/kafka-avro#initialize-kafka-avro) part of the documentation? Please provide more information as to the exact nature of your problem

**Comment by tannad** [comment]
Hi,

No I haven't followed the Initialize kafka-avro. Herewith the information: I want to consume / read the topic from the kafka cluster based on avro schema. The kafka cluster connects with Kerberos authentication / SASL.  With node-rdkafka and avsc  it didn't work and then I tried with avro-js package and it results in error. I was looking for package that would help with avro schema. 

Looking at the kafka-avro, I was just wondering the status of it. If that could be the option.

Best regards,
D Tanna

**Comment by thanpolas** [comment]
If node-rdkafka and avsc didn't work then most likely kafka-avro will not work either as it depends on those packages.

**Comment by tannad** [comment]
If it depends on those package, what additional value does kafka-avro provide?

**Comment by thanpolas** [comment]
> The kafka-avro library is a wrapper that combines the node-rdkafka and avsc libraries to allow for Production and Consumption of messages on kafka validated and serialized by Avro.

It's a helper that does some of the boilerplate required to get setup. Further boilerplate, and more opinionated one, can be found in the [node-kafking](https://github.com/waldophotos/node-kafking) package.

**Comment by tannad** [comment]
Thanks for the reply. I initialize kafka-avro , it is ready to use but when the consumer is called it errors out with the following message:
Ready to use
{ Error: Local: Timed out
    at Function.createLibrdkafkaError [as create] (/Users/<userid>/mydevelopment/Kafka/kavro/node_modules/node-rdkafka/lib/error.js:254:10)
    at /Users/<userid>/mydevelopment/Kafka/kavro/node_modules/node-rdkafka/lib/client.js:340:42
  message: 'Local: Timed out',
  code: -185,
  errno: -185,
  origin: 'kafka' }

Can you please help?

**Comment by thanpolas** [comment]
Hey, @tannad that looks like a connectivity issue. Make sure the kafka brokers are online and accessible by your application.

**Comment by tannad** [comment]
Hi,
My rdkafka consumer application is able to connect and fetch me messages form the topic. This messages are in binary, I would like to have them deserialised.  See example:
{"value":{"type":"Buffer","data":[0,0,0,0,7,250,231,195,163,189,88,72,49,66,70,67,56,52,52,51,45,53,51,53,56,45,52,49,54,50,45,65,57,56,69,45,50,54,54,53,65,70,70,57,48,51,56,52,205,204,204,204,204,204,236,63]},"size":56,"key":{"type":"Buffer","data":[49,66,70,67,56,52,52,51,45,53,51,53,56,45,52,49,54,50,45,65,57,56,69,45,50,54,54,53,65,70,70,57,48,51,56,52]},"topic":"xyz","offset":3188141,"partition":0,"timestamp":1520053025297} 
I think Kafka-avro is the way forward but then, 
In the kafka-avro:  I am struggling with the connection and also notice different property, 'metadata.broker.list' and 'kafkaBroker' , why not have the same connection property?  
I hope you can help.

Best regards,
D Tanna

**Comment by thanpolas** [comment]
As much as I want to help I cannot afford to dive into your particular use case and problem. This is an open source project and it operates under that premise. 

You will have to figure out your connectivity problems. If you come up with a bug or an enhancement suggestion please do create an issue and at best try to also provide a solution in the way of a Pull Request.
