### ISSUE TITLE
Unhandled rejection Error: Local: Broker transport failure

### ISSUE THREAD

**Issue by tannad** [waldophotos/kafka-avro#28]
Hi,

After the kafka-avro initialization and getting the message ready getting the following error: 
Unhandled rejection Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/Users/xxxx/mydevelopment/Kafka/node_modules/kafka-avro/node_modules/node-rdkafka/lib/error.js:254:10)
    at /Users/xxxx/mydevelopment/Kafka/node_modules/kafka-avro/node_modules/node-rdkafka/lib/client.js:201:30
    at /Users/xxxx/mydevelopment/Kafka/node_modules/kafka-avro/node_modules/node-rdkafka/lib/client.js:342:9
Can you kinldy help?

Many thanks,
 D Tanna

**Comment by thanpolas** [comment]
You'll have to take this to the [Blizzard/node-rdkafka](https://github.com/Blizzard/node-rdkafka) folks and open an issue there.
