### ISSUE TITLE
Schema validation on publish?

### ISSUE THREAD

**Issue by ScottChapman** [waldophotos/kafka-avro#35]
I am not clear how this is done. I poked through the code, and it looks like you get the schema for the topic, but I don't see how the validation is done exactly?

Thanks in advance.

**Comment by ricardohbin** [comment]
@ScottChapman the validation and parse is made using the [avsc](https://github.com/mtth/avsc) lib.

**Comment by ScottChapman** [comment]
Cool, I figured that was the best lib to use for that sort of thing.

But just so I know where inthe code is that taking place?

**Comment by ScottChapman** [comment]
Thanks!
