### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 when running npm install

### ISSUE THREAD

**Issue by jonathanmv** [waldophotos/kafka-avro#51]
Hello everyone,

I'm trying to install this module into my project but I get the following error
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [librdkafka.1.dylib] Error 1
make[1]: *** [libs] Error 2
make: *** [88679b727fa5c22c41a05490f93df34949b97955.intermediate] Error 2
rm 88679b727fa5c22c41a05490f93df34949b97955.intermediate
```

I'm using a macOS High Sierra Version: 10.13.6 (17G65)
My node version is v8.10.0
My npm version is 6.4.1

What other information can I provide to you? 
How can I help you to solve this?

Please let me know. Thank you

**Comment by giannisp** [comment]
@jonathanmv got `librdkafka` installed? (`brew install librdkafka`)

**Comment by jonathanmv** [comment]
I found [this step in node-rdkafka](https://github.com/Blizzard/node-rdkafka#mac-os-high-sierra). Basically for macOS High Sierra I need to set up env vars before running npm install

```
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
```

Then I ran `npm install` and the package got installed normally.
