### ISSUE TITLE
Key not being serialized

### ISSUE THREAD

**Issue by rajat12a** [waldophotos/kafka-avro#55]
Is there any reason of key not being serialized, since python kafka avro module serializes both key and value whereas this node module serializes only value

**Comment by ricardohbin** [comment]
Hello @rajat12a, you are right: currently, kafka-avro only serializes the message, not keys. But the key schemas are in memory, so in one next release I can add this support to this. I will give a look.

How the python client doesn't allow "string keys" (like the java client), probably you will have problems with the current version :/

**Comment by rajat12a** [comment]
@ricardohbin is it possible if I can contribute to your idea of 2.0.0?

**Comment by ricardohbin** [comment]
https://github.com/waldophotos/kafka-avro/pull/58 fix this right?

**Comment by rajat12a** [comment]
yes
