### ISSUE TITLE
checkForAllVersions is lost in code refactoring

### ISSUE THREAD

**Issue by manikawnth-abg** [waldophotos/kafka-avro#56]
At the end of schema registration, `.then(this._checkForAllVersions);` was used in `init` logic before.

In v.1.0.0.
```javascript
SchemaRegistry.prototype.init = Promise.method(function () {
  log.info('init() :: Initializing SR, will fetch all schemas from SR...');

  return this._fetchTopics()
    .bind(this)
    .then(this._storeTopics)
    .map(this._fetchLatestVersion, { concurrency: 10 })
    .filter(Boolean)
    .map(this._fetchSchema, { concurrency: 10 })
    .map(this._registerSchemaLatest)
    .then(this._checkForAllVersions);
});
```

in latest version:

```javascript
SchemaRegistry.prototype._fetchSchemas = function () {
  log.debug('_fetchSchemas() :: Schemas refreshed');
  return this._fetchTopics()
    .bind(this)
    .then(this._storeTopics)
    .map(this._fetchLatestVersion, { concurrency: 10 })
    .filter(Boolean)
    .map(this._fetchSchema, { concurrency: 10 })
    .map(this._registerSchemaLatest);
};
```
 
`.then(this._checkForAllVersions);`  was lost, ultimately making the functionality dead

Looks like there's something else too; as just adding this line is not deserializing it rightly..

**Edit** - For my case, I had to increase the concurrency to 50 and it solved the problem. Please add the checkforAllVersions logic in the final code.

**Comment by ricardohbin** [comment]
I will check it @manikawnth-abg , thanks for the gotcha! I already see the commit that removes this. I will make a PR here.
