### ISSUE TITLE
Passing no key fails

### ISSUE THREAD

**Issue by Meisolsson** [waldophotos/kafka-avro#64]
From what I you should be able to NOT pass a key to kafka and still have it create a message. Currently what happends if i don't pass anything (or pass an empty string) is that the produce fails.

In the code we pass null the the node-rdkafak `produce` method and that is not allowed (see https://blizzard.github.io/node-rdkafka/current/Producer.html#produce). I propse that we alway call `_serializeType` for the key (at https://github.com/waldophotos/kafka-avro/blob/bfa67f079e447be8126340105fe1e04df3ed9980/lib/kafka-producer.js#L109-L111) so even if the key is not defined we produce a empty buffer.

**Comment by ricardohbin** [comment]
@Meisolsson in `produce` method? Please can you provide what arguments is causing the breaking?

**Comment by Meisolsson** [comment]
Well if you call `kafkaProducer.produce('topic', -1, { a: 'Some data' }, '')` the event will not be produced. The check `var sendKey = key ? ... : null` return null which is not allowed by node-rdkafka.

**Comment by ricardohbin** [comment]
@Meisolsson if you pass empty string `''` the message is produced with success, the only side effect is that the consumer receives the key as `null` instead of `''`. 

Tested here with kafka-avro `1.2.0`

**Comment by Meisolsson** [comment]
Alright, might have been something else but I can't remember now. I'll close this.
