### ISSUE TITLE
How to handle schema compatibility?

### ISSUE THREAD

**Issue by psalot** [waldophotos/kafka-avro#67]
I need to implement forward or full schema compatibility.Is there any such configuration available in this library as specified [here](https://docs.confluent.io/current/schema-registry/schema_registry_tutorial.html#schema-evolution-and-compatibility) ?

**Comment by ricardohbin** [comment]
Hi @psalot , usually this is defined directly in schema-registry - and the [schema-registry-ui](https://github.com/Landoop/schema-registry-ui) provides this interface (example at http://schema-registry-ui.demo.lenses.io/#/) . The lib only reads form there
