### ISSUE TITLE
Missing timestamps on produced messages

### ISSUE THREAD

**Issue by ehrlichja** [waldophotos/kafka-avro#68]
Hi, and first off thanks for making this library.

Today I had a weird situation when I restarted my brokers and my producers to do an upgrade. After the cluster came back, I found that many of the messages being produced had -1 as their timestamp (using kafkacat). I am setting the timestamp specifically in the code:

> producer.produce(topic, -1, value, key, eventTsMs);

I know that eventTsMs value is correct at this point, because the same variable also gets serialized inside the message value, and it is a normal timestamp in there. 

Even long after the restart, one of the producers was creating null (-1) timestamped messages. Then I restarted it, and the timestamps went back to normal. 

What do you think could have caused this? Should I be looking more at the broker or the producer? Is it likely to be in node-rdkafka? librdkafka?

**Comment by ehrlichja** [comment]
I see that in https://github.com/edenhill/librdkafka/blob/v0.11.6/CONFIGURATION.md the default for 
```broker.version.fallback``` is 0.9.0. Did 0.9.0 support timestamps? Maybe ApiVersionRequest would have failed during the broker restart, and then the client chose to use a version that didn't have timestamp support.

**Comment by ricardohbin** [comment]
Hi @ehrlichja , thanks for the feedback.

Hmmm, very weird uh? The timestamp is directly in body and once produced, the broker that handles all. You get logs of your producer sending -1 timestamp or you detect this in consumer?

**Comment by ehrlichja** [comment]
I was using the kafkacat util to print just the message timestamp, which is how I was seeing the -1.

I am pretty sure the problem was that one of the producers failed to complete the version request metadata call to the broker, and so it fell back to 0.9.0, which did not support timestamps. So it must have just produced messages without timestamps, and kafkacat will show -1 for a non-existent timestamp.

Anyway, now that I know about this setting, I can just tell my producers to always use >= 0.10 since those are what my brokers are.

**Comment by ricardohbin** [comment]
Hmmm makes sense :)
