### ISSUE TITLE
Where is validation actually done?

### ISSUE THREAD

**Issue by mk0y** [waldophotos/kafka-avro#69]
Hi all,
I read in the docs that kafka-avro serialises and validates the data. So from your example I don't see anything stopping any invalid message from being sent:

```js
kafkaAvro.getProducer({
  // Options listed bellow
})
    // "getProducer()" returns a Bluebird Promise.
    .then(function(producer) {
        var topicName = 'test';

        producer.on('disconnected', function(arg) {
          console.log('producer disconnected. ' + JSON.stringify(arg));
        });

        var value = {name:'John'};
        var key = 'key';

        // if partition is set to -1, librdkafka will use the default partitioner
        var partition = -1;
        producer.produce(topicName, partition, value, key);
    })
```

I registered avro files to Schema Registry but whatever I send as `value` is being sent to the topic. Is there a use case where `.produce` method will actually fail or return error because data doesn't match the schema? Or I have basic misunderstanding of this..
Thanks in advance!

**Comment by ricardohbin** [comment]
Yep! In these cases `avsc` will raises an error, like "Error: invalid "string": undefined"
