### ISSUE TITLE
Version 2.0.0 uses a version of node-rdkafka that is broken

### ISSUE THREAD

**Issue by macabu** [waldophotos/kafka-avro#72]
This commit https://github.com/waldophotos/kafka-avro/commit/fef8aeb1f9bdb6075d980d004d21d66a4ccc5b89 updated the `node-rdkafka` to `2.7.1`,  however, the version requires NodeJS 12.  
The problem is that on `NodeJS 12.x`, `node-rdkafka@2.7.1` does not compile.  
Version `2.7.2` fixes this issue.  

```
error node-rdkafka@2.7.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.16.3"
error Found incompatible module.
```

**Comment by ricardohbin** [comment]
I tested with node 8 TLS, 10 TLS and node 11 and everything is ok. It is breaking with node12...

Let's wait some news in node-rdkafka
