### ISSUE TITLE
Unable to get relative time offset for "now minus X days"

### ISSUE THREAD

**Issue by leehambley** [waldophotos/kafka-avro#76]
For a number of services in my organization we are required to replay state from the last few days to get "clean".

We have messages that arrive very frequently (in the order of minutes) and events that are only to be seen daily, if at all. In order to calculate the state of the world we may need to start "yesterday at midnight" or "at the beginning of the calendar month" or "about 30 days ago".

In the Java APIs `getOffsetsForTimes` exists ([read more](https://stackoverflow.com/a/45221513/119669)) which gives a relative offset given a timestamp, our colleges in the org who use Java make extensive use of this.

The similar API can exist on `rdkafka` itself, kinda ([read more](https://github.com/Blizzard/node-rdkafka#reading-current-offsets-from-the-broker-for-a-topic))

`node-kafka` provides `kafka.Offsets(client)` ([read more](https://stackoverflow.com/a/38593986/119669)) 

None of these options in Node.js land are anywhere near as elegant as those in the Java world, and unfortunately I'm neither a Java programmer nor a Kafka expert, it's entirely possible that I'm just clueless on how to access this information via the `kafkaAvro` instance.

Any pointers are appreciated, else I can try and write this up on StackOverflow and hope for the best over there.

**Comment by thanpolas** [comment]
Implementing `getOffsetsForTimes` yourself and submitting it on `node-rdkafka` would probably be your best bet if that is what you want to do. After all, this package, is but a thin wrapper of that underlying, yet core, library.

However, I would recommend you rethink the problem and try to come up with alternative solutions. For this particular case, it might make sense to have an index of these topics on a different data store, where you will store date and offset key/value pairs.

**Comment by leehambley** [comment]
Thanks for the suggestion. For the time being I've solved this by also using `node-kafka` (which is dumb, but just to get an offset, it works OK).

I'll close this issue for now. The tricky part is/was that this is neither a consumer, nor a producer related concept, it's actually orthogonal and is something you need to know before starting a consumer,
